### PR TITLE
Support some more string encodings; UTF-8 in particular

### PR DESCRIPTION
**Pull request by chris-allan**
Follow on from #196 and support some more string encodings. Also when a particular encoding is chosen (ISO-8859-1 in particular), use it rather than always encoding in UTF-8. I am assuming this was the intent for the `TILEDB_STRING_ASCII` type but let me know whether pure US-ASCII was actually intended. This should make TileDB-Java compatible with all the string encodings that are currently possible via TileDB-Py.

/cc @kkoz, @erindiel

### CODE REVIEW

**Review by gsvic — CHANGES_REQUESTED** [review]
Thank you for the contribution @chris-allan! The PR looks good, the only concern is that we should preferably use the `ISO_8859_1` encoding in both `TILEDB_STRING_ASCII` and `TILEDB_CHAR` as both are intended to be ASCII and use the `UTF_8` encoding only in `TILEDB_UTF8` data type.
+ @Shelnutt2

**Comment by chris-allan** [comment]
No problem. Just let me know what you decide and I can make that change. Since I think everything is UTF-8 encoded on the Python side there's really not a precedent set for the ASCII encodings there.

**Comment by gsvic** [comment]
> No problem. Just let me know what you decide and I can make that change. Since I think everything is UTF-8 encoded on the Python side there's really not a precedent set for the ASCII encodings there.

Hi @chris-allan. If you could just make a change for handling `TILEDB_CHAR` and `TILEDB_STRING_ASCII` the same way (`ISO_8859_1`) it would be great. This is the only change needed.

**Review by gsvic — APPROVED** [review]
LGTM!

**Comment by chris-allan** [comment]
@Shelnutt2 / @gsvic: Anything else you would like done here?

**Comment by gsvic** [comment]
> @Shelnutt2 / @gsvic: Anything else you would like done here?

Merged!

**Pull request merged**
