### PR TITLE
Add string metadata support

### PR DESCRIPTION
**Pull request by chris-allan**
Add string metadata support and expand test cases accordingly.

/cc @kkoz, @erindiel

### CODE REVIEW

**Review by Shelnutt2 — APPROVED** [review]
Thanks for the contribution!

**Review by gsvic — APPROVED** [review]
LGTM! Thank you @chris-allan!

**Comment by chris-allan** [comment]
👍 Thanks guys.

Only thought I had was whether `String` return values on read would be useful? Right now you have to know you'll get a `byte[]` back, what encoding was used, etc. How are you guys handling strings in the other languages? I look only briefly at the way TileDB-Py is doing this:

https://github.com/TileDB-Inc/TileDB-Py/blob/2c26865dbb10204430c349fe63c65d6a36035c78/tiledb/libmetadata.pyx#L53-L58

**Comment by gsvic** [comment]
Hey @chris-allan -- Could you take a look at the Util class which provides a String manipulation method for turning bytes with offsets into a list of strings? This might be helpful https://github.com/TileDB-Inc/TileDB-Java/blob/master/src/main/java/io/tiledb/java/api/Util.java

**Pull request merged**
